### ISSUE TITLE
Sometimes warning for CSS syntax are not shown

### ISSUE THREAD

**Issue by hudochenkov** [stylelint/stylelint-demo#155]
Given CSS:

```css
div {
  background-image: url(
    "data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>");
}
div {
  background-image: url("data:image/svg+xml;utf8,<svg fill='black' height='24' viewBox='0 0 24 24' width='24' xmlns='http://www.w3.org/2000/svg'><path d='M7 9l5 5 5-5z'/></svg>"
  );
}

.hello {
  background-image: url("data:image/svg+xml;utf8,\
    <svg fill='black' height='24' \
    viewBox='0 0 24 24' width='24' \
    xmlns='http://www.w3.org/2000/svg'\
    ><path d='M7 9l5 5 5-5z'/></svg>");
}
```

Config:

```js
{
  "rules": {
    "max-line-length": 50,
    "string-no-newline": true
  }
}
```

Demo with syntax set to Scss, and CLI (with autodetected syntax, which is CSS) show following warnings:

```
  3:159  ✖  Expected line length to be no more than 50 characters   max-line-length  
  6:177  ✖  Expected line length to be no more than 50 characters   max-line-length  
 11:51   ✖  Unexpected newline in string                            string-no-newline
```

But demo with syntax set to CSS shows: “✔ No warnings”.
